from pathlib import Path
import subprocess
from Bio import SeqIO
from Bio import Phylo
from matplotlib import pyplot as plt
from src.logger import logger
import shutil

def build_tree(config):
    """
    Infers a phylogenetic tree using IQ-TREE and renders a rooted visualization.

    This function extracts the dynamically tagged outgroup from the provided alignment 
    and executes IQ-TREE as a subprocess to perform Maximum Likelihood tree inference 
    with ultrafast bootstrap approximation. Upon successful execution, it parses the 
    resulting '.treefile' and generates a publication-quality PNG figure of the 
    ladderized tree using Matplotlib and Biopython's Phylo module.

    Args:
        config (dict): A configuration dictionary containing execution parameters 
            and file paths. It must adhere to the following structure:
            {
                "Query": {"organism": str},
                "paths": {
                    "alignment": str, 
                    "tree": str, 
                    "figure_tree": str
                },
                "tree": {
                    "model": str, 
                    "bootstrap_num": int, 
                    "threads": int, 
                    "seed": int
                }
            }

    Returns:
        None. The function generates several IQ-TREE output files (including the 
        '.treefile') and writes the final PNG image directly to disk.

    Raises:
        KeyError: If any required nested keys are missing from the `config` dictionary.
        FileNotFoundError: If the input alignment file is missing, or if the expected 
            output '.treefile' is not generated by IQ-TREE.
        ValueError: If no sequence prefixed with 'outgroup_' is found in the alignment.
        RuntimeError: If the 'iqtree' executable is not installed/accessible in the 
            system's PATH, or if the IQ-TREE subprocess exits with an error code.
    """
    
    try:
        organism = config["Query"]["organism"]
        alignments_path = config["paths"]["alignment"]
        tree_path = config["paths"]["tree"]
        treepng_path = config["paths"]["figure_tree"]
        model = config["tree"]["model"]
        bootstrap = config["tree"]["bootstrap_num"]
        threads = config["tree"]["threads"]
        seed = config["tree"]["seed"]
        
    except KeyError as missing_key:
        logger.error(f"Configuration error. Missing key: {missing_key}")
        raise KeyError(f"Missing required configuration key: {missing_key}")
    
    if not Path(alignments_path).is_file():
        logger.error(f"Alignment file not found: {alignments_path}")
        raise FileNotFoundError(f"Alignment file not found: {alignments_path}")
      
    Path(tree_path).parent.mkdir(parents=True, exist_ok=True)
     
    outgroup_id = None
    for record in SeqIO.parse(alignments_path, "fasta"):
        if record.id.lower().startswith("outgroup_"):
            outgroup_id = record.id
            break    
        
    if outgroup_id is None:
        logger.error("No outgroup sequence found in alignment")
        raise ValueError("No outgroup sequence found in alignment")
    
    iqtree_path = shutil.which("iqtree")

    if iqtree_path is None:
        logger.error("IQ-TREE not found in PATH. Install it with:\n  conda install -c bioconda iqtree\nOr download from: https://github.com/iqtree/iqtree/releases")
        raise RuntimeError("IQ-TREE not found in PATH. Install it with:\n" "  conda install -c bioconda iqtree\n" "Or download from: https://github.com/iqtree/iqtree/releases")

    result = subprocess.run([iqtree_path, "-s", alignments_path, "-o", outgroup_id, "-m", model, "-bb", str(bootstrap), "-nt", str(threads) , "-seed", str(seed), "-pre", tree_path, "-redo"], capture_output=True, text=True)
    
    if result.returncode != 0:
        logger.error(f"IQ-TREE failed:\n{result.stderr}, {result.stdout}")
        raise RuntimeError(f"IQ-TREE failed:\n{result.stderr}, {result.stdout}")
     
    if not Path(tree_path + ".treefile").is_file():
        logger.error(f"IQ-TREE finished, but could not find the expected output tree: {tree_path + '.treefile'}")
        raise FileNotFoundError(f"IQ-TREE finished, but could not find the expected output tree: {tree_path + '.treefile'}")
    
    tree = Phylo.read(tree_path + ".treefile", "newick")

    Path(treepng_path).parent.mkdir(parents=True, exist_ok=True)

    tree.ladderize()

    fig, ax = plt.subplots(figsize=(16, 12)) 

    Phylo.draw(tree, axes=ax, do_show=False, show_confidence=True)
    plt.title(f"Phylogenetic Tree of {organism} (Rooted)", fontsize=16, pad=20)
    plt.tight_layout()
    plt.savefig(treepng_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
        
    logger.info(f"Tree figure saved to: {treepng_path}")
    